export const SITE = {
  name: "Moja psihoterapija",
  nameCyrillic: "Моја психотерапија",
  url: "https://mojapsihoterapija.com",
  phone: "+381 60 01 69 070",
  phoneRaw: "+381600169070",
  email: "info@mojapsihoterapija.com",
  instagram: "https://www.instagram.com/mojapsihoterapija_?igsh=dGM2MHVnbzJ4YTky",
  whatsapp: "https://wa.me/381600169070",
  viber: "viber://chat?number=381600169070",
  address: {
    city: "Beograd",
    cityEn: "Belgrade",
    area: "Vračar",
    country: "Srbija",
    countryEn: "Serbia",
  },
  therapist: {
    name: "Miroslav Jovanović",
    title: "Sistemski psihoterapeut",
    titleEn: "Systemic Psychotherapist",
  },
  pricing: {
    min: 18000,
    max: 25000,
    currency: "RSD",
    sessionsPerCycle: 4,
  },
} as const;

export const NAV_ITEMS = {
  sr: [
    { label: "Početna", href: "/sr/" },
    {
      label: "Oblasti rada",
      href: "/sr/oblasti-rada/",
      children: [
        { label: "Anksioznost", href: "/sr/oblasti-rada/anksioznost/" },
        { label: "Stres", href: "/sr/oblasti-rada/stres/" },
        { label: "Samopouzdanje", href: "/sr/oblasti-rada/samopouzdanje/" },
        { label: "Tuga i depresija", href: "/sr/oblasti-rada/tuga-depresija/" },
        { label: "Gubici", href: "/sr/oblasti-rada/gubici/" },
        { label: "Asertivnost", href: "/sr/oblasti-rada/asertivnost/" },
        { label: "Produktivnost", href: "/sr/oblasti-rada/produktivnost/" },
        { label: "Međuljudski odnosi", href: "/sr/oblasti-rada/medjuljudski-odnosi/" },
        { label: "Partnerski odnosi", href: "/sr/oblasti-rada/partnerski-odnosi/" },
        { label: "Bračne i porodične krize", href: "/sr/oblasti-rada/bracne-porodicne-krize/" },
        { label: "Roditeljstvo", href: "/sr/oblasti-rada/roditeljstvo/" },
        { label: "Rad sa adolescentima", href: "/sr/oblasti-rada/rad-sa-adolescentima/" },
        { label: "LGBTQAI+", href: "/sr/oblasti-rada/lgbtqai/" },
      ],
    },
    { label: "Vaš terapeut", href: "/sr/vas-terapeut/" },
    { label: "Blog", href: "/sr/blog/" },
    { label: "Kontakt", href: "/sr/kontakt/" },
  ],
  en: [
    { label: "Home", href: "/en/" },
    {
      label: "Areas of Work",
      href: "/en/areas-of-work/",
      children: [
        { label: "Anxiety", href: "/en/areas-of-work/anxiety/" },
        { label: "Stress", href: "/en/areas-of-work/stress/" },
        { label: "Self-Confidence", href: "/en/areas-of-work/self-confidence/" },
        { label: "Sadness & Depression", href: "/en/areas-of-work/sadness-depression/" },
        { label: "Grief & Loss", href: "/en/areas-of-work/grief-loss/" },
        { label: "Assertiveness", href: "/en/areas-of-work/assertiveness/" },
        { label: "Productivity", href: "/en/areas-of-work/productivity/" },
        { label: "Interpersonal Relationships", href: "/en/areas-of-work/interpersonal-relationships/" },
        { label: "Partner Relationships", href: "/en/areas-of-work/partner-relationships/" },
        { label: "Marriage & Family Crises", href: "/en/areas-of-work/marriage-family-crises/" },
        { label: "Parenting", href: "/en/areas-of-work/parenting/" },
        { label: "Working with Adolescents", href: "/en/areas-of-work/adolescents/" },
        { label: "LGBTQAI+", href: "/en/areas-of-work/lgbtqai/" },
      ],
    },
    { label: "Your Therapist", href: "/en/your-therapist/" },
    { label: "Blog", href: "/en/blog/" },
    { label: "Contact", href: "/en/contact/" },
  ],
} as const;
